"""init

Revision ID: 1c21c80e2628
Revises: 
Create Date: 2026-09-02 10:31:32.469959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c21c80e2628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.Enum('imu_ingest', name='backgroundjobtype'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False, comment='JSON字符串，如 {"sample_id": 123}'),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='backgroundjobstatus'), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_type', sa.Enum('raw_video', 'raw_imu_csv', 'ai_label_json', 'clip_video', name='mediafiletype'), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'annotator', 'reviewer', name='userrole'), nullable=False),
    sa.Column('is_outsourced', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.SmallInteger(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("is_outsourced = 0 OR role = 'annotator'", name='chk_users_outsourced_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False, comment='如 task.claim / task.reclaim_timeout'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='如 task / sample / user'),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True, comment='JSON字符串，附加上下文'),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_definitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['label_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_code', sa.String(length=64), nullable=False),
    sa.Column('dog_id', sa.String(length=64), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('video_cam1_path', sa.String(length=500), nullable=False),
    sa.Column('video_cam2_path', sa.String(length=500), nullable=False),
    sa.Column('video_cam3_path', sa.String(length=500), nullable=False),
    sa.Column('imu_csv_path', sa.String(length=500), nullable=False),
    sa.Column('ai_label_path', sa.String(length=500), nullable=True),
    sa.Column('video_duration_sec', sa.Integer(), nullable=True),
    sa.Column('video_fps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('video_resolution', sa.String(length=20), nullable=True),
    sa.Column('imu_sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('imu_row_count', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('import_status', sa.Enum('pending', 'verified', 'error', name='importstatus'), nullable=False),
    sa.Column('import_error', sa.String(length=500), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_code')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sa.Enum('from_scratch', 'ai_assisted', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_ASSIGN', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'REJECTED', name='taskstatus'), nullable=False),
    sa.Column('segment_start_ms', sa.Integer(), nullable=True),
    sa.Column('segment_end_ms', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.BigInteger(), nullable=True),
    sa.Column('round_no', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('locked_by', sa.BigInteger(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(segment_start_ms IS NULL AND segment_end_ms IS NULL) OR (segment_start_ms IS NOT NULL AND segment_end_ms IS NOT NULL AND segment_end_ms > segment_start_ms)', name='chk_segment_range'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('round_no', sa.SmallInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('human_only', 'ai_revised', name='recordsourcetype'), nullable=False),
    sa.Column('result_file_path', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'round_no', name='uq_annotation_task_round')
    )
    op.create_table('clip_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('clip_source', sa.Enum('ai', 'human', name='clipsource'), nullable=False),
    sa.Column('start_time_ms', sa.Integer(), nullable=False),
    sa.Column('end_time_ms', sa.Integer(), nullable=False),
    sa.Column('camera_channel', sa.SmallInteger(), nullable=False, comment='1/2/3，三路各生成一条job'),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='clipjobstatus'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('clip_file_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('requested_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'clip_source', 'camera_channel', 'start_time_ms', 'end_time_ms', name='uq_clip_dedup')
    )
    op.create_table('review_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('round_no', sa.SmallInteger(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='reviewdecision'), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'round_no', name='uq_review_task_round')
    )
    op.create_table('annotation_label_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('annotation_record_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time_ms', sa.Integer(), nullable=False),
    sa.Column('end_time_ms', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ai_generated', 'human_added', name='labelitemsource'), nullable=False),
    sa.Column('is_modified', sa.Boolean(), nullable=False, comment='AI标签是否被人工修改过'),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotation_record_id'], ['annotation_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_label_items')
    op.drop_table('review_records')
    op.drop_table('clip_jobs')
    op.drop_table('annotation_records')
    op.drop_table('tasks')
    op.drop_table('samples')
    op.drop_table('label_definitions')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('media_files')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
